[versions]
bedrockify = "1.11.5+mc1.21.11"
enhancedblockentities = "0.11.3+1.21.4"
fabric-api = "0.143.5+26.1"
fabric-loader = "0.18.4"
fabric-minecraft = "26.1-alpha.10"
iris = "1.10.5+1.21.11-fabric"
java = "25"
minecraft = "26.1-snapshot-10"
modmenu = "18.0.0-alpha.5"
sodium = "0.8.4+mc1.21.11"

[libraries]
bedrockify = { module = "maven.modrinth:bedrockify", version.ref = "bedrockify" }
enhancedblockentities = { module = "maven.modrinth:ebe", version.ref = "enhancedblockentities" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
sodium-api = { module = "net.caffeinemc:sodium-fabric-api", version.ref = "sodium" }
sodium-fabric = { module = "net.caffeinemc:sodium-fabric", version.ref = "sodium" }

[plugins]
fabric-loom = "net.fabricmc.fabric-loom:1.15.5"
