[versions]
bedrockify = "1.11.3+mc1.21.9"
enhancedblockentities = "0.11.3+1.21.4"
fabric-api = "0.141.2+26.1"
fabric-loader = "0.18.4"
fabric-minecraft = "26.1-alpha.2"
iris = "1.10.3+1.21.11-fabric"
java = "25"
minecraft = "26.1-snapshot-2"
modmenu = "18.0.0-alpha.3"
sodium = "mc1.21.11-0.8.1-fabric"

[libraries]
bedrockify = { module = "maven.modrinth:bedrockify", version.ref = "bedrockify" }
enhancedblockentities = { module = "maven.modrinth:ebe", version.ref = "enhancedblockentities" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }

[plugins]
fabric-loom = "net.fabricmc.fabric-loom:1.14.10"
