[versions]
bedrockify = "1.10.2+mc1.21.4"
enhancedblockentities = "0.11.3+1.21.4"
fabric-api = "0.119.6+1.21.5"
fabric-loader = "0.16.13"
fabric-minecraft = "1.21.5"
iris = "1.8.10+1.21.5-fabric"
java = "21"
minecraft = "1.21.5"
modmenu = "14.0.0-rc.2"
sodium = "mc1.21.5-0.6.12-fabric"

[libraries]
bedrockify = { module = "maven.modrinth:bedrockify", version.ref = "bedrockify" }
enhancedblockentities = { module = "maven.modrinth:ebe", version.ref = "enhancedblockentities" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }

[plugins]
fabric-loom = "fabric-loom:1.10.5"
