[versions]
commons-compress = "1.26.0"
commons-io = "2.14.0"
commons-lang3 = "3.18.0"
guava = "32.0.1-jre"
log4j = "2.12.4"
minecraft-log4j = "2.17.1"
netty-all = "4.1.94.Final"
netty-codec-http = "4.1.108.Final"
netty-codec-http2 = "4.1.100.Final"
netty-common = "4.1.118.Final"
netty-handler = "4.1.118.Final"

[libraries]
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
minecraft-log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "minecraft-log4j" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty-all" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty-codec-http" }
netty-codec-http2 = { module = "io.netty:netty-codec-http2", version.ref = "netty-codec-http2" }
netty-common = { module = "io.netty:netty-common", version.ref = "netty-common" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty-handler" }

[bundles]
loom = [ "log4j-core" ]
minecraft = [
    "commons-compress",
    "commons-lang3",
    "commons-io",
    "guava",
    "minecraft-log4j-core",
    "netty-all",
    "netty-codec-http",
    "netty-codec-http2",
    "netty-common",
    "netty-handler",
]
