# Modified version of build-tag.yml from CaffeineMC/sodium-fabric
# https://github.com/CaffeineMC/sodium-fabric/blob/aa613ca1ffeaeede666fe83faf31881b95caace1/.github/workflows/build-tag.yml

# Used when a commit is tagged and pushed to the repository
# This makes use of caching for faster builds and uploads the resulting artifacts
name: build-tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract current branch name
        shell: bash
        # bash pattern expansion to grab branch name without slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "branch=${ref////-}" >> $GITHUB_OUTPUT
        id: ref

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Initialize caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-tag-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-tag-

      - name: Build artifacts
        run: ./gradlew -Dorg.gradle.jvmargs="-Xmx2G" build -Pbuild.release=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: simply-no-shading-artifacts-${{ steps.ref.outputs.branch }}
          path: '**/build/libs/*.jar'
          compression-level: 9
