name: Pull Request Build
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Shorten SHA
        shell: bash
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: -Pversion=${{ env.short_sha }}-alpha.pr.${{ github.event.number }} build --stacktrace
      - name: Capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
